package mr

import (
	"encoding/json"
	"fmt"
	"hash/fnv"
	"io"
	"net/rpc"
	"os"
	"sort"
	"time"
)

// Map functions return a slice of KeyValue.
type KeyValue struct {
	Key   string
	Value string
}

type ByKey []KeyValue

func (a ByKey) Len() int           { return len(a) }
func (a ByKey) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a ByKey) Less(i, j int) bool { return a[i].Key < a[j].Key }

// use ihash(key) % NReduce to choose the reduce
// task number for each KeyValue emitted by Map.
func ihash(key string) int {
	h := fnv.New32a()
	h.Write([]byte(key))
	return int(h.Sum32() & 0x7fffffff)
}

// main/mrworker.go calls this function.
func Worker(mapf func(string, string) []KeyValue, reducef func(string, []string) string) {
	for {
		args := TaskArgs{}
		reply := TaskReply{}
		if !call("Coordinator.AssignTask", &args, &reply) {
			return
		}

		switch reply.TaskType {
		case TaskMap:
			if doMapTask(mapf, &reply) == nil {
				reportFinished(TaskMap, reply.TaskID)
			}
		case TaskReduce:
			if doReduceTask(reducef, &reply) == nil {
				reportFinished(TaskReduce, reply.TaskID)
			}
		case TaskWait:
			time.Sleep(1 * time.Second)
		case TaskExit:
			return
		}
	}
}

func doMapTask(mapf func(string, string) []KeyValue, reply *TaskReply) error {
	// Read the input file
	file, err := os.Open(reply.Filename)
	if err != nil {
		return err
	}
	content, err := io.ReadAll(file)
	if err != nil {
		file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}

	// Partition key/value pairs by calling mapf
	kva := mapf(reply.Filename, string(content))
	buckets := make([][]KeyValue, reply.NReduce)
	for _, kv := range kva {
		reduceID := ihash(kv.Key) % reply.NReduce
		buckets[reduceID] = append(buckets[reduceID], kv)
	}

	// Write one intermediate file for each reduce partition
	for reduceID, bucket := range buckets {
		outputName := fmt.Sprintf("mr-%d-%d", reply.TaskID, reduceID)
		tempFile, err := os.CreateTemp(".", "mr-tmp-*")
		if err != nil {
			return err
		}
		encoder := json.NewEncoder(tempFile)
		for _, kv := range bucket {
			if err := encoder.Encode(&kv); err != nil {
				tempFile.Close()
				os.Remove(tempFile.Name())
				return err
			}
		}
		tempName := tempFile.Name()
		os.Rename(tempName, outputName)
		tempFile.Close()
	}
	return nil
}

func doReduceTask(reducef func(string, []string) string, reply *TaskReply) error {

	intermediate := []KeyValue{}
	// Read the partition generated by every map task
	for mapID := 0; mapID < reply.NMap; mapID++ {
		name := fmt.Sprintf("mr-%d-%d", mapID, reply.TaskID)
		file, err := os.Open(name)
		if err != nil {
			return err
		}
		decoder := json.NewDecoder(file)
		for {
			var kv KeyValue
			err = decoder.Decode(&kv)
			if err == io.EOF {
				break
			}
			if err != nil {
				file.Close()
				return err
			}
			intermediate = append(intermediate, kv)
		}
		file.Close()
	}

	// Sort intermediate key/value pairs by key
	sort.Sort(ByKey(intermediate))

	// Write the reduce result to a temporary file
	tempFile, err := os.CreateTemp(".", "mr-reduce-*")
	if err != nil {
		return err
	}

	// Group equal keys and call reducef once for each key
	for i := 0; i < len(intermediate); {
		j := i + 1
		for j < len(intermediate) && intermediate[j].Key == intermediate[i].Key {
			j++
		}
		values := make([]string, 0, j-i)
		for k := i; k < j; k++ {
			values = append(values, intermediate[k].Value)
		}
		output := reducef(intermediate[i].Key, values)
		if _, err := fmt.Fprintf(tempFile, "%v %v\n", intermediate[i].Key, output); err != nil {
			tempFile.Close()
			os.Remove(tempFile.Name())
			return err
		}
		i = j // Continue from the first entry with a different key
	}
	tempName := tempFile.Name()
	outputName := fmt.Sprintf("mr-out-%d", reply.TaskID)
	os.Rename(tempName, outputName)
	tempFile.Close()
	return nil
}

func reportFinished(taskType TaskType, taskID int) {
	args := FinishTaskArgs{
		TaskType: taskType,
		TaskID:   taskID,
	}
	reply := FinishTaskReply{}
	call("Coordinator.FinishTask", &args, &reply)
}

// example function to show how to make an RPC call to the coordinator.
//
// the RPC argument and reply types are defined in rpc.go.
func CallExample() {

	// declare an argument structure.
	args := ExampleArgs{}

	// fill in the argument(s).
	args.X = 99

	// declare a reply structure.
	reply := ExampleReply{}

	// send the RPC request, wait for the reply.
	// the "Coordinator.Example" tells the
	// receiving server that we'd like to call
	// the Example() method of struct Coordinator.
	ok := call("Coordinator.Example", &args, &reply)
	if ok {
		// reply.Y should be 100.
		fmt.Printf("reply.Y %v\n", reply.Y)
	} else {
		fmt.Printf("call failed!\n")
	}
}

// send an RPC request to the coordinator, wait for the response.
// usually returns true.
// returns false if something goes wrong.
func call(rpcname string, args interface{}, reply interface{}) bool {
	// c, err := rpc.DialHTTP("tcp", "127.0.0.1"+":1234")
	sockname := coordinatorSock()
	c, err := rpc.DialHTTP("unix", sockname)
	if err != nil {
		return false
	}
	defer c.Close()

	err = c.Call(rpcname, args, reply)
	if err == nil {
		return true
	}

	fmt.Println(err)
	return false
}
